--
-- QUAN LY CUA HANG TIEN LOI
--

--
-- GRANT CHẠY TRÊN SYS
--

CREATE USER John IDENTIFIED BY JOHN;
GRANT CREATE SESSION TO John;
ALTER USER John QUOTA 10M ON USERS;

CREATE OR REPLACE PACKAGE pkg_CrUser
as