--
-- QUAN LY CUA HANG TIEN LOI
--

--
-- TABLESPACE
--

CREATE TABLESPACE KHACHHANG DATAFILE 'D:\app\nauQ\oradata\orcl\server01.dbf' SIZE 100M AUTOEXTEND OFF, 'D:\app\nauQ\oradata\orcl\server02.dbf' SIZE 100M AUTOEXTEND OFF;
CREATE TABLESPACE NHANVIEN DATAFILE 'D:\app\nauQ\oradata\orcl\serverNV01.dbf' SIZE 100M AUTOEXTEND OFF;

--
-- PROFILE
--

CREATE PROFILE app_user
LIMIT FAILED_LOGIN_ATTEMPTS 3
SESSIONS_PER_USER 2
CPU_PER_SESSION UNLIMITED
CPU_PER_CALL 3000
IDLE_TIME 2
PASSWORD_LOCK_TIME 1/48
PASSWORD_LIFE_TIME 30
PASSWORD_GRACE_TIME 7
PASSWORD_REUSE_TIME 365;

