--
-- QUAN LY CUA HANG TIEN LOI
--

--
-- TABLE
--

-- Bang SANPHAM
CREATE TABLE SANPHAM (
  MASP VARCHAR2(128),
  TENSP NVARCHAR2(100) NOT NULL,
  DONGIA FLOAT DEFAULT 0 CHECK (DONGIA >= 0),
  SOLUONG INT DEFAULT 0 CHECK (SOLUONG >= 0),
  LOAISP NVARCHAR2(30) NOT NULL,
  CONSTRAINT PK_SANPHAM PRIMARY KEY (MASP),
  CONSTRAINT UQ_SANPHAM UNIQUE (TENSP)
);
/

-- Bang TAIKHOAN
CREATE TABLE TAIKHOAN (
  MATK VARCHAR2(128),
  TENDANGNHAP CHAR(60) NOT NULL,
  MATKHAU NVARCHAR2(30) NOT NULL,
  LOAITK NVARCHAR2(20) NOT NULL CHECK (LOAITK IN ('Admin', 'User')),
  MATKQUANLY VARCHAR2(128),
  CONSTRAINT PK_TAIKHOAN PRIMARY KEY (MATK),
  CONSTRAINT UQ_TAIKHOAN UNIQUE (TENDANGNHAP),
  CONSTRAINT FK_TAIKHOAN_QUANLY FOREIGN KEY (MATKQUANLY) REFERENCES TAIKHOAN(MATK)
);
/

-- Bang THONGTINTK 
CREATE TABLE THONGTINTK (
  MATK VARCHAR2(128),
  TENTK NVARCHAR2(100) NOT NULL,
  SODIENTHOAI VARCHAR2(128) NOT NULL,
  DIACHI NVARCHAR2(500) NOT NULL,
  CONSTRAINT PK_THONGTINTK PRIMARY KEY (MATK),
  CONSTRAINT FK_TAIKHOAN_THONGTIN FOREIGN KEY (MATK) REFERENCES TAIKHOAN(MATK)
);
/

-- Bang HOADON
CREATE TABLE HOADON (
  MAHD VARCHAR2(128),
  TONGTIEN FLOAT NOT NULL CHECK (TONGTIEN >= 0),
  MATK VARCHAR2(128) NOT NULL,
  CONSTRAINT PK_HOADON PRIMARY KEY (MAHD),
  CONSTRAINT FK_TAIKHOAN FOREIGN KEY (MATK) REFERENCES TAIKHOAN(MATK)
);
/

-- Bang CHITIETHOADON
CREATE TABLE CHITIETHOADON (
  MASP VARCHAR2(128),
  MAHD VARCHAR2(128),
  TONGMUA INT NOT NULL CHECK (TONGMUA > 0),
  CONSTRAINT PK_CHITIETHOADON PRIMARY KEY (MASP, MAHD),
  CONSTRAINT FK_SANPHAM FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP),
  CONSTRAINT FK_HOADON FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD)
);
/