--
-- QUAN LY CUA HANG TIEN LOI
--

--
-- TRIGGER
--

-- RANG BUOC HASH MAT KHAU
CREATE OR REPLACE TRIGGER TRIGGER_INSERT_MATKHAU
BEFORE INSERT ON TAIKHOAN
FOR EACH ROW
BEGIN
    :NEW.MatKhau := RAWTOHEX(F_MD5_HASH(:NEW.MatKhau));
END;
/

-- RANG BUOC MA HOA SDT BANG DES
CREATE OR REPLACE TRIGGER TRIGGER_INSERT_SODIENTHOAI
BEFORE INSERT ON TAIKHOAN
FOR EACH ROW
BEGIN
    :NEW.SODIENTHOAI := RAWTOHEX(F_encryptDES(:NEW.SODIENTHOAI));
END;
/

-- RANG BUOC MA HOA DIA CHI BANG AES
CREATE OR REPLACE TRIGGER TRIGGER_INSERT_DIACHI
BEFORE INSERT ON TAIKHOAN
FOR EACH ROW
BEGIN
    :NEW.DIACHI := RAWTOHEX(F_encryptAES(:NEW.DIACHI));
END;
/

-- RANG BUOC DANG XUAT CHO SYS
CREATE OR REPLACE TRIGGER TR_LOGOUTUSER
BEFORE LOGOFF ON DATABASE
DECLARE
    v_sid VARCHAR2(10);
    v_serial VARCHAR2(10);
BEGIN
    SELECT SID, SERIAL# INTO v_sid, v_serial
    FROM V$SESSION
    WHERE USERNAME = USER AND STATUS = 'INACTIVE';
    
    FOR r IN (SELECT SID, SERIAL#
                FROM V$SESSION
                WHERE USERNAME = USER
                AND SID <> v_sid) LOOP
        EXECUTE IMMEDIATE 'ALTER SYSTEM KILL SESSION "' || r.SID || ',' || r.SERIAL# || '"';
    END LOOP;
END;
/