--
-- QUAN LY CUA HANG TIEN LOI
--

--
-- USER MAIN
--

DISCONNECT;

DROP USER DOAN CASCADE;

CREATE USER DOAN IDENTIFIED BY a1;
GRANT CREATE SESSION TO DOAN;
ALTER USER DOAN QUOTA 100M ON USERS;
GRANT CREATE TABLE TO DOAN;
GRANT EXECUTE ON DBMS_CRYPTO TO DOAN;
GRANT CREATE VIEW TO DOAN;
GRANT CREATE PROCEDURE TO DOAN;
GRANT CREATE TRIGGER TO DOAN;
GRANT CREATE USER TO DOAN;
GRANT CREATE SYNONYM TO DOAN;
GRANT SELECT ON SYS.dba_users TO DOAN;
/
SELECT SID, SERIAL# FROM v$session WHERE AUDSID = USERENV('SESSIONID');

SELECT * FROM v$session WHERE sid = 392;

SELECT sid, serial#, status, username FROM v$session;

DROP USER quangnv CASCADE;

CREATE ROLE NhanVien; 
CREATE ROLE KhachHang; 

GRANT SELECT ON DOAN.sanpham TO KhachHang;

GRANT SELECT ON DOAN.sanpham TO NhanVien;
GRANT INSERT ON DOAN.sanpham TO NhanVien;
GRANT DELETE ON DOAN.sanpham TO NhanVien;
GRANT UPDATE ON DOAN.sanpham TO NhanVien;

GRANT SELECT ON DOAN.hoadon TO NhanVien;
GRANT INSERT ON DOAN.hoadon TO NhanVien;
GRANT DELETE ON DOAN.hoadon TO NhanVien;
GRANT UPDATE ON DOAN.hoadon TO NhanVien;




